version: "3"

services:

    app:
      #build: .
      image: docker-springboot_app:latest
      ports:
        - 8080:8080
      volumes:
        - ./target:/target


    app2:
      #build: .
      image: docker-springboot_app:latest
      ports:
        - 8081:8080
      volumes:
        - ./target:/target    
